//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Nidec.Mes.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Nidec.Mes.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cbm Controller is not specified [{0}]..
        /// </summary>
        internal static string ffce00001 {
            get {
                return ResourceManager.GetString("ffce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name is not specified..
        /// </summary>
        internal static string ffce00002 {
            get {
                return ResourceManager.GetString("ffce00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}..
        /// </summary>
        internal static string ffce00003 {
            get {
                return ResourceManager.GetString("ffce00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file not found..
        /// </summary>
        internal static string ffce00004 {
            get {
                return ResourceManager.GetString("ffce00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usersettings data not found in the configuration file..
        /// </summary>
        internal static string ffce00005 {
            get {
                return ResourceManager.GetString("ffce00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found for usersettings in the configuration file..
        /// </summary>
        internal static string ffce00006 {
            get {
                return ResourceManager.GetString("ffce00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found for the [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00007 {
            get {
                return ResourceManager.GetString("ffce00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when kill the process : {0}.
        /// </summary>
        internal static string ffce00008 {
            get {
                return ResourceManager.GetString("ffce00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured : {0}.
        /// </summary>
        internal static string ffce00009 {
            get {
                return ResourceManager.GetString("ffce00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error has occurred again while handling unexpected exception..
        /// </summary>
        internal static string ffce00010 {
            get {
                return ResourceManager.GetString("ffce00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when kill the process during application initialization : {0}.
        /// </summary>
        internal static string ffce00011 {
            get {
                return ResourceManager.GetString("ffce00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [APPLICATION_HEADER] [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00012 {
            get {
                return ResourceManager.GetString("ffce00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CONNECTION_STRING] [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00013 {
            get {
                return ResourceManager.GetString("ffce00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AUTHENTIFICATE_FLAG] [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00014 {
            get {
                return ResourceManager.GetString("ffce00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SERVER_TIME_ZONE] [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00015 {
            get {
                return ResourceManager.GetString("ffce00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application configuration setting value is null.
        /// </summary>
        internal static string ffce00016 {
            get {
                return ResourceManager.GetString("ffce00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application configuration setting data not found.
        /// </summary>
        internal static string ffce00017 {
            get {
                return ResourceManager.GetString("ffce00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured remote service object creation : {0}.
        /// </summary>
        internal static string ffce00018 {
            get {
                return ResourceManager.GetString("ffce00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string is not specified..
        /// </summary>
        internal static string ffce00019 {
            get {
                return ResourceManager.GetString("ffce00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured during password encryption..
        /// </summary>
        internal static string ffce00020 {
            get {
                return ResourceManager.GetString("ffce00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured in wait progress form running..
        /// </summary>
        internal static string ffce00021 {
            get {
                return ResourceManager.GetString("ffce00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Connection error : [{0}].
        /// </summary>
        internal static string ffce00022 {
            get {
                return ResourceManager.GetString("ffce00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string llce00001 {
            get {
                return ResourceManager.GetString("llce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input login.
        /// </summary>
        internal static string llce00002 {
            get {
                return ResourceManager.GetString("llce00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Password.
        /// </summary>
        internal static string llce00003 {
            get {
                return ResourceManager.GetString("llce00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide  valid input..
        /// </summary>
        internal static string llce00004 {
            get {
                return ResourceManager.GetString("llce00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found for the user [{0}].
        /// </summary>
        internal static string llce00005 {
            get {
                return ResourceManager.GetString("llce00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid Menu..
        /// </summary>
        internal static string llce00006 {
            get {
                return ResourceManager.GetString("llce00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has occurred in the LDAP authentification process[{0}]..
        /// </summary>
        internal static string llce00007 {
            get {
                return ResourceManager.GetString("llce00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid authenticate flag 1(Ldap) or 2(Local user).
        ///Current value :[{0}]..
        /// </summary>
        internal static string llce00008 {
            get {
                return ResourceManager.GetString("llce00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm password not matching.
        /// </summary>
        internal static string llce00009 {
            get {
                return ResourceManager.GetString("llce00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input new password .
        /// </summary>
        internal static string llce00010 {
            get {
                return ResourceManager.GetString("llce00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input confirm password.
        /// </summary>
        internal static string llce00011 {
            get {
                return ResourceManager.GetString("llce00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password should not be same as old password.
        /// </summary>
        internal static string llce00012 {
            get {
                return ResourceManager.GetString("llce00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is error.Please input again!.
        /// </summary>
        internal static string llce00013 {
            get {
                return ResourceManager.GetString("llce00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been updated successfully. Please login again.
        /// </summary>
        internal static string llci00001 {
            get {
                return ResourceManager.GetString("llci00001", resourceCulture);
            }
        }
    }
}
