//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Nidec.Mes.Framework_Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Nidec.Mes.Framework_Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when loading assembly [{0}] : {1}..
        /// </summary>
        internal static string fsce00001 {
            get {
                return ResourceManager.GetString("fsce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when creating instance for cbm [{0}] : {1}..
        /// </summary>
        internal static string fsce00002 {
            get {
                return ResourceManager.GetString("fsce00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly not found in the remoting server path..
        /// </summary>
        internal static string fsce00003 {
            get {
                return ResourceManager.GetString("fsce00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly cbm xml not found in the remoting server path..
        /// </summary>
        internal static string fsce00004 {
            get {
                return ResourceManager.GetString("fsce00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when loading cbm for assembly [{0}] : {1}..
        /// </summary>
        internal static string fsce00006 {
            get {
                return ResourceManager.GetString("fsce00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when loading assembly list from server config : {1}..
        /// </summary>
        internal static string fsce00007 {
            get {
                return ResourceManager.GetString("fsce00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file not found..
        /// </summary>
        internal static string fsce00008 {
            get {
                return ResourceManager.GetString("fsce00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usersettings data not found in the configuration file..
        /// </summary>
        internal static string fsce00009 {
            get {
                return ResourceManager.GetString("fsce00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found for the [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00010 {
            get {
                return ResourceManager.GetString("fsce00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CONNECTION_STRING] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00013 {
            get {
                return ResourceManager.GetString("fsce00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MANDATORY_CHECK] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00014 {
            get {
                return ResourceManager.GetString("fsce00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SERVER_TIME_ZONE] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00015 {
            get {
                return ResourceManager.GetString("fsce00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application configuration setting value is null.
        /// </summary>
        internal static string fsce00016 {
            get {
                return ResourceManager.GetString("fsce00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application configuration setting data not found.
        /// </summary>
        internal static string fsce00017 {
            get {
                return ResourceManager.GetString("fsce00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when register the channel : {0}.
        /// </summary>
        internal static string fsce00018 {
            get {
                return ResourceManager.GetString("fsce00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel not implemented..
        /// </summary>
        internal static string fsce00019 {
            get {
                return ResourceManager.GetString("fsce00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel not registered..
        /// </summary>
        internal static string fsce00020 {
            get {
                return ResourceManager.GetString("fsce00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when starting the server : {0}.
        /// </summary>
        internal static string fsce00021 {
            get {
                return ResourceManager.GetString("fsce00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when register the service receiver..
        /// </summary>
        internal static string fsce00022 {
            get {
                return ResourceManager.GetString("fsce00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_SAP_CONFIG_NAME] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00023 {
            get {
                return ResourceManager.GetString("fsce00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_SAP_CONFIG_LOGON_GROUP] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00024 {
            get {
                return ResourceManager.GetString("fsce00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_SAP_CONFIG_MESSAGE_SERVER_HOST] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00025 {
            get {
                return ResourceManager.GetString("fsce00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_SAP_CONFIG_SYSTEM_ID] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00026 {
            get {
                return ResourceManager.GetString("fsce00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_SAP_CONFIG_SYSTEM_NUMBER] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00027 {
            get {
                return ResourceManager.GetString("fsce00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_SAP_CONFIG_USER] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00028 {
            get {
                return ResourceManager.GetString("fsce00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_SAP_CONFIG_PASSWORD] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00029 {
            get {
                return ResourceManager.GetString("fsce00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_SAP_CONFIG_CLIENT] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00030 {
            get {
                return ResourceManager.GetString("fsce00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_SAP_CONFIG_LANGUAGE] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00031 {
            get {
                return ResourceManager.GetString("fsce00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerConfigurationDataTypeEnum not found for the [{0}] settings..
        /// </summary>
        internal static string fsce00032 {
            get {
                return ResourceManager.GetString("fsce00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_SAP_CONFIG_POOL_SIZE] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00033 {
            get {
                return ResourceManager.GetString("fsce00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_SAP_CONFIG_PEAK_CONNECTIONS_LIMIT] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00034 {
            get {
                return ResourceManager.GetString("fsce00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_SAP_CONFIG_IDLE_TIMEOUT] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00035 {
            get {
                return ResourceManager.GetString("fsce00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_SAP_CONFIG_IDLE_CHECKTIME] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00036 {
            get {
                return ResourceManager.GetString("fsce00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when kill the process during application initialization : {0}.
        /// </summary>
        internal static string fsce00037 {
            get {
                return ResourceManager.GetString("fsce00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_PQM_CONFIG_URL] [{0}] in the configuration file..
        /// </summary>
        internal static string fsce00038 {
            get {
                return ResourceManager.GetString("fsce00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly list not found in the server config..
        /// </summary>
        internal static string fsci00001 {
            get {
                return ResourceManager.GetString("fsci00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cbmcontrollerid [{0}] not found..
        /// </summary>
        internal static string fsci00002 {
            get {
                return ResourceManager.GetString("fsci00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel registered successfully..
        /// </summary>
        internal static string fsci00003 {
            get {
                return ResourceManager.GetString("fsci00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service receiver registered successfully..
        /// </summary>
        internal static string fsci00004 {
            get {
                return ResourceManager.GetString("fsci00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NidecMES server started successfully.....
        /// </summary>
        internal static string fsci00005 {
            get {
                return ResourceManager.GetString("fsci00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify and restart the server..
        /// </summary>
        internal static string fsci00006 {
            get {
                return ResourceManager.GetString("fsci00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015 service registraion successful..
        /// </summary>
        internal static string fsci00007 {
            get {
                return ResourceManager.GetString("fsci00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2008 service registraion successful..
        /// </summary>
        internal static string fsci00008 {
            get {
                return ResourceManager.GetString("fsci00008", resourceCulture);
            }
        }
    }
}
